{% set name = "ConnectionPool" %}
{% set author = "jmeppley" %}
{% set version = "0.1.0" %}
{% set sha256 = "123861f0ff0b7d0967d2fb3cbefd13a461091be7a5451942f820c7f17062669f" %}

package:
  name: simple_connection_pool
  version: {{ version }}

source:
    fn: {{ name }}.{{ version }}.tar.gz
    url: https://github.com/jmeppley/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/{{ author }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple thread-safe pure-python connection pool'

extra:
  recipe-maintainers:
    - {{ author }}
